# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyCPU/project_23/project_23.srcs/sources_1/ip/my_unsigned_div/my_unsigned_div.xci
# IP: The module: 'my_unsigned_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyCPU/project_23/project_23.gen/sources_1/ip/my_unsigned_div/my_unsigned_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_unsigned_div'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/MyCPU/project_23/project_23.srcs/sources_1/ip/my_unsigned_div/my_unsigned_div.xci
# IP: The module: 'my_unsigned_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyCPU/project_23/project_23.gen/sources_1/ip/my_unsigned_div/my_unsigned_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_unsigned_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
